### ISSUE TITLE
Userstories Mapview

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#108]
Als gebruiker wil ik ..

- [x] tussen de verschillende kaartlagen in een bundel* kunnen schakelen.
- [x] een legenda kunnen zien behorende bij de geselecteerde kaart laag
- [x] kunnen zoeken en navigeren naar een adres

* Per organisatie dient de bundel met kaartlagen door FM ingesteld te worden

**Comment by pnobbe** [comment]
Closing for now as this seems done, please reopen if incorrect @DonZandbergen @yorickdewid
