### ISSUE TITLE
Manifest file is not generated

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMapsClientApp#11]
The application manifest file causes an error. Likely because there is no manifest file and so the index (HTML) is served.

**Comment by WvanDam** [comment]
Ha. I just recalled this issue and disabled that html line as a possible fix for the edge issue. Manifest file actually does exist. There is something with the generated href: `<link rel="manifest" href="<%= BASE_URL %>site.webmanifest">`

**Comment by WvanDam** [comment]
Hmm... the `name` in the manifest is empty.

**Comment by WvanDam** [comment]
Or actually. Opening the path directly leads to a 404, generated by Vue. The file isn’t being routed to...

**Comment by yorickdewid** [comment]
I'd rather have the manifest file than disabling the link

**Comment by yorickdewid** [comment]
Seems to be resolved
