### ISSUE TITLE
Adres lookup in Mapviewer

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#126]
Opzoeken van een adres in een searchbar in de kaartweergave en vervolgens daarop centreren.

Uitgangspunten:

- Het opgezochte adres in het midden van het de kaart centreren.
- Zoomniveau van 18 aanhouden
- searchbar linksboven in kaartweergave opnemen.
- Alleen adressen als suggestie opnemen binnen de contour van account toevoegen

**Comment by pnobbe** [comment]
Fixed in b81a576aa38534cf8b401881f8abacc99f0e8e8f
