### ISSUE TITLE
Toevoegen adressen

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#14]
**Toevoegen adressen onder nieuw toegevoegd rapport**

Adres 1 toevoegen ("+ Adres toevoegen") ==> niet het adres "opslaan" ==> Adres 2 toevoegen ("+ Adres toevoegen") ; Ingevulde gegevens bij Adres 1 worden dan geleegd. 

![image](https://user-images.githubusercontent.com/46600362/67079721-fbe3af00-f193-11e9-8960-09661568f1b9.png)

**Comment by WvanDam** [comment]
Zal ik dit zodanig verhelpen dat de knop toevoegen ook alle niet opgeslagen samples opslaat, gelijk aan de volgende stap knop?

**Comment by DonZandbergen** [comment]
lijkt inderdaad een goede oplossing. Zie wel issue #15

**Comment by DonZandbergen** [comment]
Na adres 2 toevoegen ("+ Adres toevoegen") is het voorgaande ingevulde adres (Adres 1) opgeslagen. Ook de header van het adresblok tont het adres. De velden met sample-data zijn echter leeg. Na F5 zijn deze gevuld.

**Comment by DonZandbergen** [comment]
![image](https://user-images.githubusercontent.com/46600362/67094588-73c1d180-f1b4-11e9-907d-921e1a979f67.png)

**Comment by WvanDam** [comment]
Foutmelding in screenshot was ivm issue #15. Het aanmaken van twee samples achter elkaar was een issue ivm een refresh van de weergave op basis van de reeds opgeslagen data, terwijl de api call nog onderweg was. Omdat er anders te makkelijk data issues ontstaan door het ontbreken van `id`s op meerdere samples wordt het opslaan nu eerst volledig afgehandeld, voordat een nieuwe sample kan worden toegevoegd.

**Comment by DonZandbergen** [comment]
Wanneer er reeds adressen aan een rapport zijn toegevoegd en er nog een adres wordt toegevoegd:
Na invullen van alle sample-velden in een adres => niet opslaan => nieuw adres toevoegen;

Alle sample-velden worden opgeslagen op het veld FUNDERINGSTYPE na. 
FUNDERINGSTYPE  rijgt de waarden van een veld het adres ouder dan de voorgaande toegevoegd adres. 

Het veld ONDERBOUW geeft "selecteer optie". Dit veld wordt geheel niet opgeslagen door "opslaan", "+ nieuwe adres" of "volgende".



![image](https://user-images.githubusercontent.com/46600362/67149431-7eab5d80-f2ab-11e9-8d2f-c8756c3e7c8c.png)
