### ISSUE TITLE
Add "Scheuren" step

### ISSUE THREAD

**Issue by pnobbe** [Laixer/FunderMapsClientApp#147]
![image](https://user-images.githubusercontent.com/8037254/107255081-3aac1100-6a38-11eb-858a-e814b56671c7.png)

## FIELDS BELOW APPLY TO EVERY TYPE OF TEAR DEFINED AS FOLLOWS:
- Inpandige scheur
- Voorgevel scheur
- Achtergevel scheur
- Linkergevel scheur
- Rechtergevel scheur

| Field | Input type | Data type | Default | Required? | Condition | 
| - | - | - | - | - | - |
| Enabled | RadioImageInput | `Boolean` | `False` | Yes | |
| Hoeveel scheuren | Number input | `Number` `x` | 0 |  No | `this.enabled` |
| Hersteld | RadioTextInput | `Boolean` | `null` |  Yes | `this.enabled` |
| Scheur `x` [mm] | Number input | `Number` (Double) | `null` | Yes | `this.enabled` |

**Comment by pnobbe** [comment]
Is 5 the limit for the amount of tears? If not, element stacking for length input should probably be vertical.

**Comment by pnobbe** [comment]
Remove scheurcount input field, add plus button to add new row

Rows determine tear count, length and restoration per tear

**Comment by pnobbe** [comment]
Add type of tear to tear data (enum crack_type)

**Comment by DonZandbergen** [comment]
Alle scheuren opnemen in 'mm'
