### ISSUE TITLE
Pop-up kaartweergave 

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#152]
In de pop-up bij de kaartweergave moeten voor de volgende lagen een link worden opgenomen naar de rapportage waarin de sample is vastgelegd.

Lagen waarbij de link moet worden opgenomen:

- Funderingstype vastgesteld
- Rapport
- Kwaliteit
- Handhavingstermijnen
- Oorzaak schade

Uitgangspunten:

- Wanneer er meerdere rapporten een adres beschrijven, alle linken opnemen
- Links open in new window

Back-end gereed: 
https://github.com/Laixer/FunderMaps/issues/419

**Comment by DonZandbergen** [comment]
Welke link wordt getoond wanneer er meerdere rapporten aan 1 pand zijn gekoppeld.
(als het goed is de meest recente, zo is de kaart opgebouwd)

**Comment by pnobbe** [comment]
Fixed in 6bcd4d386ed7597369ec932ab086b698daeb7bb7
