### ISSUE TITLE
deleting a sample while unsaved samples exist will remove all unsaved samples from the list

### ISSUE THREAD

**Issue by pnobbe** [Laixer/FunderMapsClientApp#159]

**Comment by DonZandbergen** [comment]
1. Voeg adres toe en vul waarden in => opslaan
2. Nieuw adres en vul waarden in (NIET opslaan)
3. Verwijder eerder toegevoegd adres
4. Het niet opgeslagen adres is nu cleared.

**Comment by yorickdewid** [comment]
Difficult to change with the current design
