### ISSUE TITLE
Weergave "verwerker" en "reviewer"

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#16]
In stap 3 van toevoegen van rapportage worden de "verwerker" en "reviewer" niet bij naam genoemd.

![image](https://user-images.githubusercontent.com/46600362/67080156-e753e680-f194-11e9-82e4-64af8c44e01c.png)

**Comment by WvanDam** [comment]
Ah, dit zal dan ook effect hebben op de pagina waar het rapport wordt weergegeven.

**Comment by WvanDam** [comment]
@yorickdewid hiervoor heb ik toch in het attribution deel van de report GET call een beknopt user / org objecten nodig, met id & naam om hier weer te geven, e.g.

````
reviewer: {
  id: 'uuid',
  name: 'user / org name'
},
````

Het front-end zou dit meteen goed moeten afhandelen als jij de api response aanpast.

**Comment by DonZandbergen** [comment]
Voor een revieuwer zijn nu de knoppen "goedkeuren" en "afkeuren"niet meer zichtbaar.

**Comment by WvanDam** [comment]
Geregeld in de front-end code door de naam op basis van id op te halen uit de lijst van actieve reviewers. Idem voor uitvoerende organisaties. De verwerker is verborgen omdat er geen informatie beschikbaar is van deze gebruikers.

Notitie: dit is een tijdelijke oplossing. Op termijn zal het voorkomen dat actieve reviewers verdwijnen, waardoor de naam van de betreffende reviewers niet meer op basis van id gekoppeld kan worden aan rapportages waaraan de inactieve reviewers zijn verbonden. 

Er zijn echter plannen om op relatief korte termijn de data rechtstreeks beschikbaar te stellen uit de API.

**Comment by DonZandbergen** [comment]
Informatie van de verwerker is de ingelogde user. Die komt ook terug in de user-list bij de organisatie.

**Comment by WvanDam** [comment]
Klopt, maar die informatie wordt enkel opgehaald door superusers, op de organisatie pagina.

**Comment by DonZandbergen** [comment]
check
