### ISSUE TITLE
Lege adresregel klaarzetten

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#164]
Standaard beginnen met een (leeg) aangemaakt adres.

![image](https://user-images.githubusercontent.com/46600362/109553442-55bbef00-7ad3-11eb-9f94-ff1274655877.png)

**Comment by pnobbe** [comment]
Fixed in da867d44c6a3c5ed21b2cd91d9d2ac466f5f672c
