### ISSUE TITLE
Aanpassen teamlid

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#17]
Als organisatiebeheerde (superuser) dient bij "oraganisatie" temaleden kunnen worden aangemaakt en aangepast.

Aanpassen is niet mogelijk door disabled veld voor email. En aanmaken lijkt niet goed terug opgehaald te worden (geen gegevens zichtbaar).

**bewerken teamlid**
![image](https://user-images.githubusercontent.com/46600362/67080591-d788d200-f195-11e9-8c2e-a0412b080565.png)

**Aanmaken nieuw teamlid**
![image](https://user-images.githubusercontent.com/46600362/67080697-0bfc8e00-f196-11e9-9d97-56d8ff99ec70.png)

**Comment by WvanDam** [comment]
@yorickdewid had jij reeds de deploy gedaan met de nieuwe response structuur op de profile call?

**Comment by yorickdewid** [comment]
Nee nog niet

**Comment by yorickdewid** [comment]
Nu wel

**Comment by WvanDam** [comment]
@yorickdewid Users worden in het panel geladen via id referentie. Het id wordt nu niet meer meegestuurd vanuit de API. Zal ik overstappen op email?

**Comment by yorickdewid** [comment]
Nee nog steeds op id. Pas het zo aan

**Comment by yorickdewid** [comment]
Every profile contains a user id

**Comment by DonZandbergen** [comment]
opgelost door email te verbergen
