### ISSUE TITLE
Opslaan Adressen

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#18]
Opslaan adressen via knop "opslaan" (per adres) als voor allemaal via "volgende" geeft een 500.
Front-end geeft per adres terug: "De wijzigingen zijn niet opgeslagen"

![image](https://user-images.githubusercontent.com/46600362/67094298-df576f00-f1b3-11e9-9c74-4736c7ba69bb.png)

**Comment by yorickdewid** [comment]
Backend issue, done
