### ISSUE TITLE
Rapport bewerken

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#19]
Bij een bestaand rapport bewerken geeft de knop "volgende" een 500.

![image](https://user-images.githubusercontent.com/46600362/67094884-f8145480-f1b4-11e9-9459-313bfdbdebf5.png)

**Comment by WvanDam** [comment]
@yorickdewid De API call van het opslaan van de samples is niet gewijzigd. Kan het zijn dat je het endpoint nog aan het herstellen was nadat we afzagen van de omschakeling van 1 sample naar meerdere samples opslaan via deze api?

**Comment by yorickdewid** [comment]
Mogelijk gefixed, was gelerateerd aan een andere bug

**Comment by WvanDam** [comment]
Dit is volgens mij inderdaad verholpen.

**Comment by DonZandbergen** [comment]
verholpen
