### ISSUE TITLE
Knop opslaan

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#21]
De knop "opslaan" voert geen actie uit.

![image](https://user-images.githubusercontent.com/46600362/67149552-c088d380-f2ac-11e9-9c18-c6992df0c4e4.png)

**Comment by WvanDam** [comment]
De knop is nu verbonden aan de logische actie die hoort bij de stap die in beeld is.
1: opslaan & naar stap 2
2: opslaan & naar stap 3
3: aanbieden ter review
