### ISSUE TITLE
Wijzigen UITVOERDER en REVIEWER

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#22]
Wijzigen van de UITVOERDER en REVIEWER in stap 1 van wizard bij rapportage worden niet opgeslagen.

![image](https://user-images.githubusercontent.com/46600362/67150823-c2f32980-f2bc-11e9-9c18-958231a323e6.png)

**Comment by yorickdewid** [comment]
By design, these are not supposed to be changed later?! However the frontend is not aware of this restriction.

**Comment by DonZandbergen** [comment]
True, Then it should not be a possibilty as a feature. Disable fields?

**Comment by WvanDam** [comment]
ok. Klinkt eenvoudig, maar dat is het helaas niet. Een field disabled maken is natuurlijk geen probleem. Het probleem zit hem in het bepalen wanneer wel / niet. 

Ik kan simpelweg de velden disabled maken wanneer iemand het rapport bewerkt, maar technisch gezien bewerk je ook een bestaand rapport wanneer je de stappen voor het eerst doorloopt en van stap 2 terug gaat naar 1. Ook dan wordt het document opgehaald uit de API.

**Comment by DonZandbergen** [comment]
check. Dat is ook niet de oplossing.
@yorickdewid  Wijzigingen opnemen in design/API een idee?
Wijkt af van design, hoeft geen probleem te zijn in de feature.
