### ISSUE TITLE
Keuren door reviewer

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#23]
Bij rapportages die zijn aangeboden voor review blijft de alert-bar staan na GOEDKEUREN, melding 403.

![image](https://user-images.githubusercontent.com/46600362/67150863-82e07680-f2bd-11e9-835f-fa9c363f4421.png)

**Comment by yorickdewid** [comment]
Possibly related to #24

**Comment by DonZandbergen** [comment]
Niet in relatie tot #24 (#24 is verwerkt en opgelost), dit doet zich nog voor.

**Comment by WvanDam** [comment]
Ik zie kort door de bocht drie redelijke mogelijkheden:
1. De gebruiker heeft geen review rechten, maar krijgt de review opties toch in beeld
2. De rechten controle aan het back-end is niet overeenkomstig met de huidige rechten structuur
3. Het pad van de api call is gewijzigd, waardoor het pad op een ontoegankelijk punt uit komt

**Comment by yorickdewid** [comment]
403 seems unrelated, the banner does not seem to automatically disappear

**Comment by DonZandbergen** [comment]
done
