### ISSUE TITLE
Review mogelijkheid

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#24]
Bij nieuw geüploade rapportages wordt functionaliteit voor het goedkeuren en afkeuren voor de reviewer niet getoond wanneer het rapport is aangeboden ter review.  Er is tevens een melding 403.

![image](https://user-images.githubusercontent.com/46600362/67150912-1e71e700-f2be-11e9-9dbd-93dcd05c2fba.png)

**Comment by yorickdewid** [comment]
Workaround is made available

**Comment by DonZandbergen** [comment]
verwerkt
