### ISSUE TITLE
Veld FUNDERINGSTYPE & ONDERBOUW

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#25]
Wanneer er reeds adressen aan een rapport zijn toegevoegd en er nog een adres wordt toegevoegd:
Na invullen van alle sample-velden in een adres => niet opslaan => nieuw adres toevoegen;

Alle sample-velden worden opgeslagen op het veld FUNDERINGSTYPE na. 
FUNDERINGSTYPE  rijgt de waarden van een veld het adres ouder dan de voorgaande toegevoegd adres. 

Het veld ONDERBOUW geeft "selecteer optie". Dit veld wordt geheel niet opgeslagen door "opslaan", "+ nieuwe adres" of "volgende".

![image](https://user-images.githubusercontent.com/46600362/67149431-7eab5d80-f2ab-11e9-8d2f-c8756c3e7c8c.png)

_Originally posted by @DonZandbergen in https://github.com/Laixer/FunderMapsClientApp/issues/14#issuecomment-544182677_

**Comment by WvanDam** [comment]
Voor de duidelijkheid, we hebben het hier over 2 issues.

1. Bij de 2de keer dat op "adres toevoegen" wordt geklikt wordt de waarde voor "Funderingstype" niet overgenomen van het laatst ingevoerde adres. 

2. Het onderbouw veld wordt niet opgeslagen.

**Comment by WvanDam** [comment]
Wat betreft de onderbouw: deze informatie wordt wel verstuurd naar de api, volgens de specificatie die in swagger staat.

**Comment by WvanDam** [comment]
Kan het zijn dat de API geen uitgeschreven ENUMS (meer) verwacht, maar index cijfers?

**Comment by yorickdewid** [comment]
Ja dat is zeker zo, maar vaak werkt een string waarde ook. Ik ga even kijken wat er precies mis gaat

**Comment by DonZandbergen** [comment]
done
