### ISSUE TITLE
Reviewer dropdown 'leeg' omdat de opgeslagen waarde geen optie meer is

### ISSUE THREAD

**Issue by WvanDam** [Laixer/FunderMapsClientApp#26]
Het viel me net op dat `/report/95123/file/edit/1` een valid maar leeg dropdown veld weergeeft. 

Dit betreft een reviewer die niet meer geselecteerd kan worden. Omdat deze reviewer niet opgehaald wordt in de reviewer lijst kan ik deze ook niet opzoeken op het id dat beschikbaar is gesteld. Kortom, er kan enkel een leeg veld of het id van de reviewer weergegeven worden.

**Comment by yorickdewid** [comment]
Design flaw, won't fix for this release
