### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#27]
The map isn't loading due to: Invalid prop: type check failed for prop "mapStyle". Expected String, Object, got Undefined 

![image](https://user-images.githubusercontent.com/46600362/67162411-13719200-f364-11e9-9074-7bd905f1e29b.png)

**Comment by yorickdewid** [comment]
Frontend configuration missing

**Comment by yorickdewid** [comment]
Map is loading but not downloading the layers. API has not changed and seems to be working

**Comment by DonZandbergen** [comment]
Layers are selectable and are shown now
