### ISSUE TITLE
Reporttype "aanvullend onderzoek"

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#28]
When editing a report the reporttype is not set to the previously selected option.

![image](https://user-images.githubusercontent.com/46600362/67162861-c17f3b00-f368-11e9-8bbe-11c96d56dec5.png)

**Comment by yorickdewid** [comment]
Possible problem seems https://github.com/Laixer/FunderMapsClientApp/blob/04fbe3baf711b213bd9d9f262c9972a3d6671125/src/views/report/Step1.vue#L413

In which case the `typeNumber` holding a value of 0 evaluates as false, returning `null`

**Comment by DonZandbergen** [comment]
done
