### ISSUE TITLE
Saving via "opslaan" button gives 403

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#35]
The saving button performs the same action as "aanbieden ter review". That's is not correct.

- Saving via button "opslaan" = save en exit to homescreen NOT "aanbieden ter review".
- "aanbieden ter review" via button "aanbieden ter review"  = "aanbieden ter review" and exit to homescreen. 

This actions gives an 403.

![image](https://user-images.githubusercontent.com/46600362/67619598-d7c04780-f7fd-11e9-87aa-abe6597ffe2d.png)

**Comment by yorickdewid** [comment]
Save should trigger the current saving action and leaveq
