### ISSUE TITLE
Re-submit report

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#36]
When a report is declined by reviewer, then adjusted by user and re-submitted the review-proces should be re-performd. Meening a reviewer should be able tot aprove or decline a report again.

Now is stays declined.

![image](https://user-images.githubusercontent.com/46600362/67619719-26baac80-f7ff-11e9-8039-a70752d7225f.png)

Updating a declined report stays delined but schould be "in progress" again.
After submitting for review a  403 is thrown.

![image](https://user-images.githubusercontent.com/46600362/67293741-2364af80-f4e5-11e9-8ea4-f687e4197cb7.png)

**Comment by yorickdewid** [comment]
Known limitation of current release
