### ISSUE TITLE
inform user after decline

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#37]
When a report is declined by reviewer the message from an reviewer should be e-mailed to user that sumitted the report.

**Comment by yorickdewid** [comment]
Known limitation of current release. Although the internals are ready for this issue there is no real world test that can be done for now.

**Comment by yorickdewid** [comment]
@tabeckers When doing the review just validate there is a way to call for notifications/messages/mails

**Comment by tabeckers** [comment]
There exists an `INotificationService` but it's not fully implemented. Is this still correct?
