### ISSUE TITLE
F3O input

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsClientApp#50]
When "Conform F3O" is set in step 1 in the wizard, then to step 2 and back to step 1 the bullit is default on "Nee". When "Ja" was entered this must be shown.

Conform F3O need to be shown on overviewpage.

![image](https://user-images.githubusercontent.com/46600362/71920206-909fec80-3186-11ea-927a-5ad8ad07f0ed.png)

**Comment by yorickdewid** [comment]
As this is a frontend issue we won't be able to validate it until next milestone?

**Comment by DonZandbergen** [comment]
> As this is a frontend issue we won't be able to validate it until next milestone?

Correct
