### ISSUE TITLE
DocumentDate is not parsed to the correct format when posting a new inquiry in step 1

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMapsClientApp#66]
With regards to the production environment.

```
DocumentDate: ["The field DocumentDate must be between 1/1/1000 12:00:00 AM and 1/1/2100 12:00:00 AM."]
```

https://eu-prod.asyncgw.teams.microsoft.com/v1/objects/0-weu-d6-76dac6d9842d371f0b4692753c447061/views/imgo

**Comment by yorickdewid** [comment]
This only happens when document_date is selected before 1000. Limit date picker
