### ISSUE TITLE
Application does not work in MS Edge

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMapsClientApp#7]
MS Edge logs an error in the console and does not continue executing the page. The same happens in MSIE, but we do not support MSIE. We do need to support Edge as it is used in many commercial environments.

**Comment by WvanDam** [comment]
I just pushed a commit that may be a temp fix for this issue

**Comment by yorickdewid** [comment]
Not a fix for this problem

**Comment by yorickdewid** [comment]
Fixed with the transpiler
