### ISSUE TITLE
Contractor changes in inquiry wizard aren't persisted

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMapsClientApp#91]
**Steps to reproduce:**
- Uitvoerder geselecteerd 
- Naar stap 2 (form wordt opgeslagen) 
- Terug naar stap 1 
- Andere uitvoerder selecteren 
- Naar stap 2 (form wordt updated) 
- Terug naar stap 1 
- Aanpassing aan nieuw geselecteerde uitvoerder is niet opgeslagen.

**Comment by yorickdewid** [comment]
Contractor, reviewer was not updatable
