### ISSUE TITLE
Reviewer changes in inquiry wizard aren't persisted

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMapsClientApp#92]
**Steps to reproduce:**
- Reviewer geselecteerd 
- Naar stap 2 (form wordt opgeslagen) 
- Terug naar stap 1 
- Andere reviewer selecteren 
- Naar stap 2 (form wordt updated) 
- Terug naar stap 1 
- Aanpassing aan nieuw geselecteerde reviewer is niet opgeslagen

**Comment by yorickdewid** [comment]
See #91
