### ISSUE TITLE
Frontend validation feedback doesn't work correctly for inquiry samples

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMapsClientApp#93]
When we don't select a foundation quality our frontend doesn't show the field as required. The request does fail and feedback is displayed to the user about this, but not about why the request failed.

The `Funderingskwaliteit` field should be marked as invalid (red).

![image](https://user-images.githubusercontent.com/26200358/96107120-4e0cfc80-0edc-11eb-854b-a2ee30d5c32f.png)

**Comment by pnobbe** [comment]
Funderingskwaliteit was not required in the frontend, but unintentionally required in the backend. This has since been fixed.
